seed: 0

dset: cifar20
t_row: 0.1
t_col: 0.05

multi_crop: 0

num_classes: 20 # number of output classes discrete range [0,9]
num_epochs: 800 # number of times which the entire dataset is passed throughout the model
batch_size: 512 # the size of input data took for one iteration

lr: 0.4 # 1 # size of step
momentum: 0.9
weight_decay: 0.0001 # weight decay
final_lr: 4.0e-4
warmup_epochs: 10
start_warmup_value: 0.01

backbone: 'resnet18'
hidden_dim: [4096, 128]
head_sizes: [20, 40, 80, 160]

optimizer: sgd
lars: false

train_interval: 5
test_interval: 5
save_interval: 1000

# if ablation study, then set early_stop to 300
early_stop: 1000


