seed: 0

dset: mnist
t_row: 0.1
t_col: 0.05

multi_crop: 0

num_classes: 10 # number of output classes discrete range [0,9]
num_epochs: 100 # number of times which the entire dataset is passed throughout the model
batch_size: 512 # the size of input data took for one iteration

lr: 0.0004 # 1 # size of step
momentum: 0.9
weight_decay: 0
final_lr: 0
warmup_epochs: 0
start_warmup_value: 0.0004

backbone: 'resnet18'
hidden_dim: [4096, 128]
head_sizes: [10, 20, 40, 80]

optimizer: adam
lars: false

train_interval: 10
test_interval: 10
save_interval: 1000
