seed: 0

dset: stl10
t_row: 0.10
t_col: 0.05

multi_crop: 0

#best row=0.07, col=0.05

num_classes: 10 # number of output classes discrete range [0,9]
num_epochs: 800 # number of times which the entire dataset is passed throughout the model
batch_size: 256 # the size of input data took for one iteration

lr: 0.4 # 1 # size of step
momentum: 0.9
weight_decay: 0.0001 # weight decay
final_lr: 4.0e-4
warmup_epochs: 10
start_warmup_value: 0.01

backbone: 'resnet18'
hidden_dim: [4096, 128]
head_sizes: [10, 20, 40, 80]

optimizer: sgd
lars: false

train_interval: 5
test_interval: 5
save_interval: 100

# if ablation study, then set early_stop to 300
early_stop: 1000
